### ISSUE TITLE
ver como sumar numeros con funcional

### ISSUE THREAD

**Issue by maurociancio** [larosamf/rescatapp#10]
https://github.com/larosamf/rescatapp/blob/734e4bd2315de9985ed3aaf1e964d8a5cdf0c603/api/src/main/java/com/rescatapp/api/domain/Transitista.java#L136

[****](https://mkyong.com/java8/java-how-to-sum-all-the-stream-integers)

evitar foreachs

**Comment by ldtejepeya** [comment]
listo
