### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by maurociancio** [larosamf/rescatapp#9]
https://github.com/larosamf/rescatapp/blob/734e4bd2315de9985ed3aaf1e964d8a5cdf0c603/api/src/main/java/com/rescatapp/api/domain/Transitista.java#L142

**Comment by Tyavicoli** [comment]
corregido

**Comment by maurociancio** [comment]
tambien veo q estan usando .getFechaDeRespuesta() y eso puede ser fechaDeRespuesta
